config/routes.rb
Posh::Application.routes.draw do
  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/news', to: 'static_pages#news', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/forum', to: 'static_pages#forum', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Site built by Rory Munro
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "News", news_path %></li>
			
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-custom navbar-fixed-top navbar">
	<div class= "navbar-inner">
		<div class= "container">
			<%= link_to image_tag("poshlogo.jpg", alt: "poshlogo", id: "poshlogo"), root_path %>
		<nav>
			<ul class= "nav pull-right">
				<li><%= link_to "HOME", root_path %></li>
				<li><%= link_to "NEWS", news_path %></li>
				
				<% if signed_in? %>
				  <li><%= link_to "FORUM", forums_path %></li>
				  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
				<% else %>
				  <li><%= link_to "ABOUT", about_path %></li>
				  <li><%= link_to "Sign in", signin_path %>
				<% end %>

			</ul>
		</nav>
		</div>
	</div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'favicon(4).ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52137961-1', 'theposh.herokuapp.com');
  ga('send', 'pageview');

</script>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div class="container", id= "main">
  	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>

<%= render 'layouts/footer' %>
  </div>
</body>
</html>